[Unit]
StartLimitIntervalSec=0

[Service]
ExecStart=
ExecStart=/nix/var/nix/profiles/default/bin/nix-daemon --daemon
Restart=always
RestartSec=3s
Slice=cybex-forge-build.slice
CPUWeight=25
IOWeight=25
OOMScoreAdjust=250
